### PR TITLE
Natural Docs Prototype

### PR DESCRIPTION
**Pull request by dgkutnic**
This is a prototype of the `TensorDim` class in C++ and Python (along with some of the functions it references). I'm looking for feedback on the general style/layout of the comments within the code as it relates to the docs that are generated (critique on the content of the comments itself is welcome too). The goal is to rapidly prototype on this class before I go and do a bunch of classes.

We'll probably have to modify the CSS too, but that can be something we do later.

### CODE REVIEW

**Comment by dgkutnic** [comment]
Side Note: integrating natural docs into bazel seems like it might be _interesting_. I'll leave that part for later since it isn't immediately critical to getting the docs out.

**Comment by flaub** [comment]
OK, I can work on the bazel build part, let's not checkin all the generated files

**Comment by dgkutnic** [comment]
I agree that we wouldn't want to check them in for an actual PR, just wanted a way to host them for now for an easier review process.

**Comment by flaub** [comment]
Actually, it's very hard for me to review since there's lots of irrelevant files in the PR.

**Comment by dgkutnic** [comment]
OK, I'll get rid of them now then.

**Comment by flaub** [comment]
@dgkutnic Are you ok if we close this PR? Seems like sphinx will work for us?

**Comment by dgkutnic** [comment]
@flaub yeah, I'm fine with closing it. I was keeping it open for reference purposes, but we've gone far enough down the Sphinx path that I'm comfortable closing this.

**Pull request closed without merging**
