### PR TITLE
Use vector type casts for ceiling and float

### PR DESCRIPTION
**Pull request by earhart**

### CODE REVIEW

**Comment by flaub** [comment]
Why doesn't our CI catch these problems? Or rather, could we add tests to this PR that exposes these issues?

**Comment by earhart** [comment]
I don’t know a good way in the current codebase to force vectorization. We could possibly build a semtree-level test framework, but that probably needs some long-term planning, not a hack for this particular case.

**Comment by flaub** [comment]
Where do these issues crop up? Wouldn't they show up in correctness or performance issues on certain targets?

**Comment by earhart** [comment]
This came up in nGraph testing. It’s a compilation error.

**Pull request merged**
