### PR TITLE
Update BatchDot to switch between TensorFlow/Theano Behavior

### PR DESCRIPTION
**Pull request by dgkutnic**
- Updated the plaidml backend code to check for the environment variable `PLAIDML_BATCHDOT_TF_BEHAVIOR` and switch between Theano (default) and TensorFlow-like behaviors.
- Updated the plaidml backend tests to set `skip_tensorflow` and `skip_theano` based on the environment variable from above
- Updated the troubleshooting docs to add instructions for using the environment variable `PLAIDML_BATCHDOT_TF_BEHAVIOR` and which runtime error it's typically associated with
- Updated the runtime message typically associated with `BatchDot` issues to direct users to the troubleshooting docs

### CODE REVIEW

**Comment by tzerrell** [comment]
I thought the test failures you had were fixed by @drgone's PR #412; if they persist, perhaps talk to him about them.

**Comment by dgkutnic** [comment]
Yeah, I've pulled in his changes and am rerunning CI now. I'll let him know if I'm still seeing failures this time around.

**Comment by drgone** [comment]
This is unrelated, base/backend is failing across all platforms.

**Comment by tzerrell** [comment]
Don't know how I missed seeing those the first time. In that case, I suspect the problem might be that we approximately never use Theano (it looks like it only is invoked in testGather and now this test, which may be relevant as the error mentions gemm and testGather does not involve matmuls). So if the install of Theano on the build machines is flakey but local installs work ok, we might see this behavior.

**Pull request merged**
