### PR TITLE
Implementation of K.any

### PR DESCRIPTION
**Pull request by Antetokounpo**
This is an implementation of K.any, like my previous pull request it's a hacky solution, let me know if anything is wrong or could be better.

### CODE REVIEW

**Comment by jinz2014** [comment]
The Keras backend function 'any' is not yet implemented in Plaid.  Sorry, is there an implementation available ? 

Thanks

**Comment by tzerrell** [comment]
Looks good! This needs unit tests though, in `plaidml/keras/backend_test.py`. I think `testSum` might be a good example of how to write such a test. Let us know if you run into any problems doing this.

**Comment by Antetokounpo** [comment]
Thank you for the reply and the help. I added the unit tests. I used `@compareForwardExact` for the tests instead of `@opTest`, because it seemed like TensorFlow didn't support derivatives for this operation, at least that's what it seemed like. 

Let me know if anything is wrong or could be improved.

**Comment by Antetokounpo** [comment]
Okay I rebased with master. Again let me know if anything is wrong.

Thanks!

**Comment by tzerrell** [comment]
The `all` PR created merge conflicts -- @Antetokounpo can you confirm that my fixes of those conflicts & the style tweaks are ok?

**Comment by Antetokounpo** [comment]
Yes they're fine. Thank you!

**Pull request merged**
