### PR TITLE
Embed heatmap into tile/targets/cpu

### PR DESCRIPTION
**Pull request by flaub**

### CODE REVIEW

**Comment by flaub** [comment]
@jbruestle @shiyao00 So should we go ahead and land this?

**Comment by flaub** [comment]
Oh, looks like it doesn't build on windows, it's too big for the parser. We'll need to come up with some alternative.

**Comment by flaub** [comment]
@shiyao00 is this safe to close now?

**Comment by shiyao00** [comment]
> @shiyao00 is this safe to close now?

Yes, please close it.

**Pull request closed without merging**
