### PR TITLE
Add missing tile dialect library dependencies

### PR DESCRIPTION
**Pull request by earhart**

### CODE REVIEW

**Comment by flaub** [comment]
I don’t think these are necessary. Can you provide more context?

**Comment by earhart** [comment]
These are necessary: I wrote some code that used this Bazel target, and the code failed at runtime because these dependencies weren't linked in.

**Comment by flaub** [comment]
Can you provide me the list of symbols that weren't resolved if you have them?

**Comment by earhart** [comment]
`verify` and `createCanonicalizerPass`.

Experimenting a bit more with my current code (since I've added some dependencies on my side), I'm still getting this, with both dependencies removed:
```
dyld: Symbol not found: __ZNK4mlir17ConversionPattern15matchAndRewriteEPNS_9OperationERNS_15PatternRewriterE
  Referenced from: _solib_darwin_x86_64//libexternal_Scom_Uintel_Uplaidml_Spmlc_Sconversion_Spxa_Uto_Uaffine_Slibpxa_Uto_Uaffine.so
```

Adding `Transforms` back in fixes this.

**Pull request merged**
