### PR TITLE
Tweak secure getenv condition

### PR DESCRIPTION
**Pull request by earhart**

### CODE REVIEW

**Comment by LLITCHEV** [comment]
In CI I see the following error...
ERROR: /data/buildkite-agent/builds/lab-13-1/plaidml/plaidml-plaidml/pmlc/rt/opencl/BUILD:33:18: Linking of rule '//pmlc/rt/opencl:clprobe' 
I'd probably also remove the following comment on line 3 in the BUILD file...
"# This file is used for detecting secure_getenv, in which case it will contain
# #define HAVE_SECURE_GETENV.
# For now leave blank to fallback to getenv."

**Review by LLITCHEV — APPROVED** [review]
Other than the last comment, it looks fine to me.

**Review by LLITCHEV — APPROVED** [review]
Looks fine to me.

**Comment by flaub** [comment]
When I merged this, it broke on my machine. I'm going to revert this in the next PR I submit.

**Pull request merged**
