### PR TITLE
Fixes to mixed col/row-major stencil pass to make it row-major

### PR DESCRIPTION
**Pull request by alheinecke**

### CODE REVIEW

**Comment by flaub** [comment]
LGTM

**Comment by flaub** [comment]
However, looks like something went wrong:
https://buildkite.com/plaidml/plaidml-plaidml/builds/2826#c22decf5-ef6f-4749-93b3-5e95132f6836

If you want more details you can go to the `artifacts` tab and then look for the following artifact:

```
bazel-testlogs/pmlc/target/x86/tests/xsmm_call.mlir.test/test.log
```

**Comment by flaub** [comment]
FYI, to run all tests locally, use:

```
bazelisk test ...
```

**Comment by alheinecke** [comment]
yeah, there were constants which my grep didn't get, now it's going through

**Pull request merged**
