### PR TITLE
Add OV Range op

### PR DESCRIPTION
**Pull request by tzerrell**
Adds a Range op (that only accepts Constants as inputs). Not tested as the "constant propagation to output causes crash" bug prevents the unit tests from working, but should hopefully be useful in practical cases. Marked as a draft until we've tried it in a practical case.

### CODE REVIEW

**Comment by tzerrell** [comment]
Still no CI due to the bug mentioned above, but I have tested a network with a Range op in it, and with the changes from my newest commit it did not crash, so IMO this is "tested enough" to land.

**Comment by YangleiZouIntel** [comment]
LGTM

**Comment by flaub** [comment]
@tzerrell Did we decide that we didn't need the range op after all since we do a constant folding pass? Should we close this one?

**Comment by tzerrell** [comment]
Yes, good point, a constant-only Range op like this is pointless with constant folding, which we now have. And we don't yet support a dynamically-shaped Range op.

**Pull request closed without merging**
