### PR TITLE
WIP OpenVino plugin one_hot

### PR DESCRIPTION
**Pull request by 1sanz**

### CODE REVIEW

**Comment by tzerrell** [comment]
Context: this is failing tests because we do not track name changes that appear to arise from OV optimizations

**Comment by flaub** [comment]
Is this PR still valid?

**Comment by tzerrell** [comment]
This is not valid to land as-is due to API changes and the move into the OV fork repo. It contains code that could still be useful for re-developing this op. Note that the mentioned error in my above comment is now documented on the OV fork as https://github.com/plaidml/openvino/issues/88

Closing as this is no longer the right target repo.

**Comment by tzerrell** [comment]
Oh, so followup: Since the code is still useful for the other repo, please don't delete the branch.

**Comment by tzerrell** [comment]
ah, mergify does that automatically? Fun :/

**Pull request closed without merging**
