### PR TITLE
correctly inherit environment variables

### LINKED ISSUE #886: ERROR Caught unhandled exception: Missing environment variable: CONDA_EXE
```log
Configuring PlaidML build environment

conda found at: C:\Users\cloud\Miniconda3\Library\bin\conda.BAT


Your build is configured.
Use the following to run all unit tests:

bazelisk test //...

INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=140
INFO: Options provided by the client:
  'build' options: --python_path=C:/Users/cloud/Miniconda3/python.exe
INFO: Reading rc options for 'build' from d:\machine_learning\plaidml\bzl\bazel.rc:
  'build' options: -c opt --spawn_strategy=standalone --genrule_strategy=standalone --announce_rc --nolegacy_external_runfiles --distinct_host_configuration=false --enable_platform_specific_config --action_env=LC_ALL --action_env=LANG --action_env=NO_PROXY --action_env=HTTP_PROXY --action_env=HTTPS_PROXY --action_env=no_proxy --action_env=http_proxy --action_env=https_proxy --define=version=0.0.0.dev0
INFO: Found applicable config definition build:windows in file d:\machine_learning\plaidml\bzl\bazel.rc: --build_tag_filters=-darwin,-docs,-latex,-linux,-metal,-pytorch --action_env=CONDA_EXE --action_env=NUMBER_OF_PROCESSORS --action_env=PLAIDML_SETTINGS --cxxopt=/std:c++17 --cxxopt=/Zc:__cplusplus
================================================================================
LIBXSMM release-1.12.1 (Windows_NT)
--------------------------------------------------------------------------------
Compiler: gcc, and g++
C / C++ target: <compiler default>
Fortran Compiler is disabled or missing: no Fortran interface is built!
--------------------------------------------------------------------------------
--- LIBXSMM build log
INFO: Analyzed target //plaidml:wheel (11 packages loaded, 18105 targets configured).
INFO: Found 1 target...
INFO: From Linking external/jsonnet/cmd/jsonnet.exe:
LINK : warning LNK4044: unrecognized option '/lm'; ignored
LINK : warning LNK4044: unrecognized option '/lm'; ignored
INFO: From Compiling Jsonnet to JSON for plaidml_link:
bazel-out/x64_windows-opt/bin/plaidml/plaidml.def
bazel-out/x64_windows-opt/bin/plaidml/plaidml.ld
bazel-out/x64_windows-opt/bin/plaidml/plaidml.lds
INFO: From Compiling external/boost/libs/regex/src/wc_regex_traits.cpp:
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\xstring(2388): warning C4244: 'argument': conversion from '_Ty' to 'const _Elem', possible loss of data
        with
        [
            _Ty=const wchar_t
        ]
        and
        [
            _Elem=char
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\xstring(2399): note: see reference to function template instantiation 'void std::basic_string<char,std::char_traits<char>,std::allocator<char>>::_Construct<_Ty*>(_Iter,const _Iter,std::input_iterator_tag)' being compiled
        with
        [
            _Ty=const wchar_t,
            _Iter=const wchar_t *
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\xstring(2399): note: see reference to function template instantiation 'void std::basic_string<char,std::char_traits<char>,std::allocator<char>>::_Construct<_Ty*>(_Iter,const _Iter,std::input_iterator_tag)' being compiled
        with
        [
            _Ty=const wchar_t,
            _Iter=const wchar_t *
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\xstring(2379): note: see reference to function template instantiation 'void std::basic_string<char,std::char_traits<char>,std::allocator<char>>::_Construct<_Ty*>(const _Iter,const _Iter,std::forward_iterator_tag)' being compiled
        with
        [
            _Ty=const wchar_t,
            _Iter=const wchar_t *
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\xstring(2379): note: see reference to function template instantiation 'void std::basic_string<char,std::char_traits<char>,std::allocator<char>>::_Construct<_Ty*>(const _Iter,const _Iter,std::forward_iterator_tag)' being compiled
        with
        [
            _Ty=const wchar_t,
            _Iter=const wchar_t *
        ]
external/boost/libs/regex/src/wc_regex_traits.cpp(228): note: see reference to function template instantiation 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>::basic_string<const wchar_t*,void>(_Iter,_Iter,const _Alloc &)' being compiled
        with
        [
            _Iter=const wchar_t *,
            _Alloc=std::allocator<char>
        ]
external/boost/libs/regex/src/wc_regex_traits.cpp(228): note: see reference to function template instantiation 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>::basic_string<const wchar_t*,void>(_Iter,_Iter,const _Alloc &)' being compiled
        with
        [
            _Iter=const wchar_t *,
            _Alloc=std::allocator<char>
        ]
ERROR: D:/machine_learning/plaidml/tile/targets/cpu/BUILD:40:1: heatmap tile/targets/cpu/heatmap.cc failed (Exit 1)
Caught unhandled exception: Missing environment variable: CONDA_EXE
Target //plaidml:wheel failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2671.115s, Critical Path: 19.50s
INFO: 381 processes: 381 local.
FAILED: Build did NOT complete successfully
```

By manually modifying https://github.com/plaidml/plaidml/blob/f2d57996958ebba7f147a0f7e00550928b6e661b/tools/conda_run/conda_windows.cc#L90 I can walkaround this issue. And the CONDA_EXE is correctly set in my case.

### PR DESCRIPTION
**Pull request by cloudhan**
fixed #886

### CODE REVIEW

**Comment by flaub** [comment]
I'm puzzled why we haven't needed this in our CI environment so far...

**Comment by cloudhan** [comment]
I cannot inspect into your ci build environment, my guess is that you are falling into the bottom case https://github.com/plaidml/plaidml/blob/f2d57996958ebba7f147a0f7e00550928b6e661b/tools/conda_run/conda_windows.cc#L89-L94
If you install miniconda into `C:\tools\Miniconda3`, all will be OK. TBH, my previous trail is to edit this path to match my case and it indeed let me produce a whl package.

**Comment by cloudhan** [comment]
OK, I tried to do a probe build in #889 and it failed to trigger a windows build (or maybe should I wait it longer, and then it will show up magically?). Anyway, I am fortunately to prove my guess with [this build](https://buildkite.com/plaidml/plaidml-plaidml/builds/2234#95191485-dbca-443c-a375-2602c8ac9571) and [the associated build log](https://buildkite.com/organizations/plaidml/pipelines/plaidml-plaidml/builds/2234/jobs/95191485-dbca-443c-a375-2602c8ac9571/download.txt)

```

FAILED: Build did NOT complete successfully
--
  | Traceback (most recent call last):
  | File "ci/buildkite.py", line 308, in <module>
  | main()
  | File "ci/buildkite.py", line 304, in main
  | args.func(args, remainder)
  | File "ci/buildkite.py", line 175, in cmd_build
  | util.check_call(['bazelisk'] + startup_args + ['test', '...'] + common_args, env=env)
  | File "C:\buildkite-agent\builds\vm-03-1\plaidml\plaidml-plaidml\ci\util.py", line 29, in check_call
  | subprocess.check_call(cmd, **kwargs)
  | File "C:\tools\Miniconda3\lib\subprocess.py", line 347, in check_call
  | raise CalledProcessError(retcode, cmd)
```

That is you are indeed install miniconda to `C:\tools\Miniconda3` and I can confirm you are falling into  the `if` code path.

**Comment by flaub** [comment]
Could you try to remove the hardcoded path so that we can see if the `use_default_shell_env` has the desired effect under the CI environment?

Thanks for helping me understand (I did misunderstand what you were saying before).

**Comment by flaub** [comment]
Thanks for being patient with me, I can see your other PR that removed the hard-coded path does in fact cause our CI system to fail:

https://buildkite.com/plaidml/plaidml-plaidml/builds/2235#f4fcb49f-ccad-404a-a2a7-2dc119272fff

**Comment by flaub** [comment]
Oddly, `use_default_shell_env` doesn't seem to fix the issue in the CI environment nor in my local windows VM. This might be a bug in bazel itself.

**Comment by cloudhan** [comment]
I forgot to mention that I am using a non-release version of bazel to walkaround another bug. IIRC, obtained from https://github.com/bazelbuild/bazel/issues/10331#issuecomment-559725478

**Comment by flaub** [comment]
Could you try with `bazelisk`? This way it will use the version of bazel specified in `.bazelversion`.

I've tried with `2.0.0` and it still fails.

Perhaps we can leave the hard-coded path in and then add the `use_default_shell_env` for now.

**Comment by cloudhan** [comment]
> Could you try with `bazelisk`? This way it will use the version of bazel specified in `.bazelversion`.
That was my first try. I met the bazel bug. So I wont try it again.

I will revert the commit.

**Pull request merged**
