### PR TITLE
Expose target registry map 

### PR DESCRIPTION
**Pull request by earhart**

### CODE REVIEW

**Comment by earhart** [comment]
FYI -- this includes changes from #1317; until that's landed, please make sure to only look at the most recent commit.

**Comment by flaub** [comment]
What new functionality does this provide?

**Comment by earhart** [comment]
I was thinking to build towards device access, going through the `Target` -- so each device is named `<target>.<device_index>`.

At some point, we might want to rename this `Target` class to something like `Api` or `Hal` or `Backend` -- something like Vulkan or OpenCL or Metal.  I don't see a need to do that just yet, though.

**Comment by earhart** [comment]
(... the primary reason for keeping the current `Target` name is because targets are the things we're currently registering, and it's really easy to change this later.)

**Comment by flaub** [comment]
It seems like we're confusing targets with devices. I think certain devices will have support for certain targets, but they should not be combined.

**Comment by earhart** [comment]
(Closing this PR -- will open a new one along the lines we've discussed.)

**Pull request closed without merging**
