### PR TITLE
Use unsigned ints instead of ints

### PR DESCRIPTION
**Pull request by LLITCHEV**
Keras expects only positove random numbers.

### CODE REVIEW

**Comment by flaub** [comment]
Hang on, this should have no effect from keras's point of view.

**Comment by flaub** [comment]
This only changes the state data type, which is completely unrelated to the result data type.

**Comment by tzerrell** [comment]
Huh. It very much appears to change the result of calls to `K.random_uniform` (producing values from `[0, 1)`, whereas w/out this change values were from `[-0.5,0.5)`). We're only manually checking what the output appears to be since the backend_test tests for these have additional errors, but the pattern was pretty clear.

**Comment by tzerrell** [comment]
Perhaps something somewhere is (incorrectly?) retaining the signedness of the state when producing the result values?

**Comment by flaub** [comment]
That's what I'm worried about, that perhaps there's some other issue.

**Comment by jbruestle** [comment]
Two things are going on here.  1) Using int32 is fundamentally incorrect and changes how the shifts are interpreted, possibly causing all sorts of issues (sorry to have overlooked that, see the code here for reference https://github.com/spotify/linux/blob/master/lib/random32.c). 2) Additionally, the output will natively produce 32 bits of 'random' bits, and to convert that to a number [0, 1), we  do a cast / division (on line 35 above), which does two different things depending on the source type, which in fact does take signedness into account exactly as one would imagine.

**Pull request merged**
