### PR TITLE
Fix assertion in reorder-layout

### PR DESCRIPTION
**Pull request by chelini**
- mlir::Block needs location info
- tensor.pad wants a different terminator

### CODE REVIEW

**Comment by chelini** [comment]
This fixes: ninja plaidbench_py && PYTHONPATH=$PWD KMP_AFFINITY=granularity=fine,verbose,compact,1,0 OMP_NUM_THREADS=8 PLAIDML_REORDER=1 python plaidbench/plaidbench.py -n50 keras resnet50

**Review by tzerrell — APPROVED** [review]
LGTM

The CI failure seemed to be transient -- that we have transient CI failures isn't ideal, but it's not a problem for this PR.

**Comment by alheinecke** [comment]
OK, let me merge... yeah it's the same thing I saw the other day... there conda setup was running into lock file issue.

**Review by alheinecke — COMMENTED** [review]
LGTM

**Comment by tzerrell** [comment]
FYI it wasn't just the conda lock transient failure, but on an earlier build (The 4th attempt by GitHub's reckoning, here: https://github.com/plaidml/plaidml/actions/runs/2389957271/attempts/4) there was a protobuf error that didn't reappear in later attempts

**Comment by alheinecke** [comment]
oh yeah... this was "worse" I'm not sure what is causing these things... and it seems to go away when we only run one step of CI at a time.

**Pull request merged**
